@echo off
echo Adding environment variables to Vercel...

echo Adding VITE_FIREBASE_PROJECT_ID...
echo eduvox-cb8f0 | vercel env add VITE_FIREBASE_PROJECT_ID production preview development

echo Adding VITE_FIREBASE_STORAGE_BUCKET...
echo eduvox-cb8f0.firebasestorage.app | vercel env add VITE_FIREBASE_STORAGE_BUCKET production preview development

echo Adding VITE_FIREBASE_MESSAGING_SENDER_ID...
echo 334132777442 | vercel env add VITE_FIREBASE_MESSAGING_SENDER_ID production preview development

echo Adding VITE_FIREBASE_APP_ID...
echo 1:334132777442:web:a3cbc82759de1875e429bb | vercel env add VITE_FIREBASE_APP_ID production preview development

echo Adding VITE_GOOGLE_API_KEY...
echo AIzaSyDpgVVotCvECy63BSnMtvMUEK71kms63jo | vercel env add VITE_GOOGLE_API_KEY production preview development

echo Adding VITE_ADSENSE_CLIENT_ID...
echo ca-pub-your-adsense-publisher-id | vercel env add VITE_ADSENSE_CLIENT_ID production preview development

echo Adding VITE_ADSENSE_BANNER_SLOT...
echo your-banner-ad-slot-id | vercel env add VITE_ADSENSE_BANNER_SLOT production preview development

echo Adding VITE_ADSENSE_ARTICLE_SLOT...
echo your-article-ad-slot-id | vercel env add VITE_ADSENSE_ARTICLE_SLOT production preview development

echo All environment variables added successfully!
